os:
- linux
language: nix
nix: 2.2.1

branches:
  only:
    - master

script:
  - nix-env -i cookiecutter
  - echo 'default_context:\n    package_name: travis-test' > config.yaml
  - cookiecutter --config-file config.yaml --no-input .
  - cd travis-test
  - nix-build --arg pkgs 'import <nixpkgs> {}' --arg withHoogle false
