os:
- linux
language: nix
nix: 2.2.1

branches:
  only:
    - master

script:
  - nix-env -i cookiecutter
  - cookiecutter --config-file ci/cookiecutter-config.yml --no-input .
  - cd travis-test
  - nix-build --arg pkgs 'import <nixpkgs> {}'
  - nix-shell --arg pkgs 'import <nixpkgs> {}' --command 'hoogle fmap --count=1'
