name: "Test minimal generated project"
on:
  pull_request:
  push:
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - name: Install nix
      uses: cachix/install-nix-action@v19
    - name: Setup cachix
      uses: cachix/cachix-action@v8
      with:
        name: alexpeits-gh-actions
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build project
      run: |
        nix-env -i cookiecutter
        cookiecutter --config-file ci/cookiecutter-config.yml --no-input .
        cd minimal-test
        nix-build
